In [1]:
import keras
from keras import backend as K
from keras.utils.np_utils import to_categorical

Using TensorFlow backend.


In [2]:
keras.backend.image_data_format()

'channels_last'

In [3]:
from quilt.data.andrewbrown import gofamiliar

In [4]:
import numpy as np

In [5]:
def rewardloss(yTrue, yPred):
    return -K.dot(yTrue, K.transpose(yPred))

In [6]:
egs = np.load(gofamiliar.positions()).shape[0]

In [7]:
all_inputs = np.load(gofamiliar.positions()).reshape(egs,9,9,3)

In [8]:
labels = to_categorical(np.load(gofamiliar.moves()))

In [9]:
labels.shape

(10430, 83)

In [59]:
inputs = keras.layers.Input(shape=(9,9,3))

In [60]:
conv = keras.layers.Convolution2D(filters=16, kernel_size=(3,3), activation='elu')(inputs)

In [61]:
flat = keras.layers.Flatten()(conv)

In [62]:
hidden = keras.layers.Dense(2**10, activation='elu')(flat)

In [63]:
bn = keras.layers.BatchNormalization()(hidden)

In [64]:
output = keras.layers.Dense(83, activation='softmax')(bn)

In [65]:
model = keras.models.Model(inputs=inputs, outputs=output)

In [66]:
model.compile(optimizer='adam', loss=rewardloss)

In [67]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 9, 9, 3)           0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 7, 7, 16)          448       
_________________________________________________________________
flatten_2 (Flatten)          (None, 784)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1024)              803840    
_________________________________________________________________
batch_normalization_2 (Batch (None, 1024)              4096      
_________________________________________________________________
dense_4 (Dense)              (None, 83)                85075     
Total params: 893,459
Trainable params: 891,411
Non-trainable params: 2,048
_________________________________________________________________


In [68]:
preds = model.predict(all_inputs[0,:,:,:].reshape(1,9,9,3))

In [69]:
np.round(preds,decimals=3)

array([[ 0.017,  0.015,  0.018,  0.01 ,  0.008,  0.013,  0.009,  0.01 ,
         0.008,  0.011,  0.017,  0.011,  0.017,  0.006,  0.029,  0.01 ,
         0.011,  0.013,  0.012,  0.012,  0.012,  0.006,  0.009,  0.011,
         0.008,  0.008,  0.009,  0.017,  0.008,  0.012,  0.009,  0.007,
         0.015,  0.009,  0.017,  0.014,  0.013,  0.015,  0.014,  0.012,
         0.008,  0.01 ,  0.015,  0.011,  0.014,  0.007,  0.012,  0.019,
         0.01 ,  0.014,  0.011,  0.014,  0.015,  0.013,  0.024,  0.006,
         0.012,  0.016,  0.009,  0.009,  0.01 ,  0.009,  0.011,  0.011,
         0.007,  0.011,  0.031,  0.009,  0.012,  0.01 ,  0.018,  0.011,
         0.016,  0.008,  0.011,  0.015,  0.006,  0.006,  0.01 ,  0.016,
         0.012,  0.006,  0.013]], dtype=float32)

In [70]:
model.fit(all_inputs, target, epochs=5, verbose=2);

Epoch 1/5
2s - loss: -8.1311e-01
Epoch 2/5
2s - loss: -8.2279e-01
Epoch 3/5
2s - loss: -8.2420e-01
Epoch 4/5
2s - loss: -8.2527e-01
Epoch 5/5
2s - loss: -8.2605e-01


In [72]:
preds = model.predict(all_inputs[0,:,:,:].reshape(1,9,9,3))
np.round(preds,decimals=3)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.]], dtype=float32)

In [73]:
all_inputs[43,:,:,:].reshape(1,3,9,9)

array([[[[0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 1, 1, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 0, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 0, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 0, 1],
         [1, 1, 0, 0, 0, 1, 1, 0, 1],
         [1, 1, 1, 0, 1, 1, 1, 1, 1],
        

In [34]:
labels[43, :81].reshape(9,9)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [77]:
pred = model.predict(all_inputs[57,:,:,:].reshape(1,9,9,3))
np.round(preds,decimals=3)[:,:81].reshape(9,9)

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]], dtype=float32)

In [51]:
target = np.load(gofamiliar.positions())[:,2,:,:] - np.load(gofamiliar.positions())[:,0,:,:] - np.load(gofamiliar.positions())[:,1,:,:]
target[0]

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1, -1,  1,  1,  1,  1, -1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1, -1,  1,  1,  1, -1,  1,  1,  1],
       [ 1, -1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1, -1,  1]], dtype=int64)

In [58]:
target = np.concatenate([target.reshape(egs, 81), -np.ones((egs,1)), -np.ones((egs, 1))], axis=1)
target[0]

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
       -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
        1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1., -1.,  1., -1., -1.])

In [75]:
target[3].shape

(83,)

In [82]:
np.sum(np.load(gofamiliar.positions())[:,2,:,:], axis=0)

array([[9518, 9485, 9496, 9491, 9369, 9459, 9441, 9525, 9524],
       [9496, 8584, 8543, 8249, 8020, 8118, 8542, 8557, 9485],
       [9429, 8519, 7588, 7874, 7710, 7738, 7777, 8597, 9489],
       [9469, 8192, 7930, 8294, 8134, 8324, 8106, 8349, 9465],
       [9452, 8102, 7943, 8299, 8137, 8299, 8131, 8198, 9414],
       [9485, 8225, 7951, 8298, 8309, 8327, 8013, 8315, 9461],
       [9552, 8565, 7704, 8001, 7978, 7896, 7693, 8571, 9512],
       [9476, 8596, 8636, 8297, 8181, 8231, 8519, 8592, 9519],
       [9463, 9498, 9461, 9462, 9449, 9495, 9499, 9507, 9541]], dtype=int64)

In [88]:
np.round(model.predict(all_inputs),decimals=3)[:, 79]

array([ 1.        ,  0.        ,  0.        , ...,  0.        ,
        1.        ,  0.81400001], dtype=float32)